### ISSUE TITLE
Change Backend port

### ISSUE THREAD

**Issue by rahu1rathore** [jonasrenault/fastapi-react-mongodb-docker#10]
How to run this backend app to a different port

**Comment by jonasrenault** [comment]
Use `uvicorn app.main:app --reload --port 8080` to start the backend on port 8080.

If you want the frontend to work with the backend running on a different port, update the `VITE_BACKEND_API_URL` in the relevant .env file, i.e. in [.env.development](https://github.com/jonasrenault/fastapi-react-mongodb-docker/blob/main/frontend/.env.development) set

```
VITE_BACKEND_API_URL=http://localhost:8080/api/v1/
```

**Comment by rahu1rathore** [comment]
where is the file start-reload.sh?? and  i want to change 'FROM tiangolo/uvicorn-gunicorn-fastapi:latest' to python 3.11 but its throw error start-reload no such file or directory

**Comment by jonasrenault** [comment]
The latest version of `tiangolo/uvicorn-gunicorn-fastapi` docker image should be using python 3.11 as per https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker .

If you look at the docker file for [tiangolo/uvicorn-gunicorn-fastapi:python3.11](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/blob/master/docker-images/python3.11.dockerfile), you can see that it's built from `tiangolo/uvicorn-gunicorn:python3.11` (without fast-api). You can find this `tiangolo/uvicorn-gunicorn:python3.11` image [here](https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/python3.11.dockerfile), and the `start-reload.sh` file [here](https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/start-reload.sh).

If you only want to change the Port used by `tiangolo/uvicorn-gunicorn-fastapi`, set the [PORT](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#port) env variable on the service running it.
