### ISSUE TITLE
Getting "Not found" error for http://localhost:8000/api/v1/docs

### ISSUE THREAD

**Issue by thameem786-ops** [jonasrenault/fastapi-react-mongodb-docker#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jonasrenault** [comment]
As mentioned in the backend's [Readme](backend/README.md), if you want to access the backend API's docs, you need to navigate to `http://localhost:8000/docs`. If you're running the application with docker, the same docs will be available from `http://localhost/docs`.
